name: Check for dead links for app
on: push
jobs:
  dead-links-check:
    runs-on: ubuntu-latest
    env:
      MONGODB_USER: ${{ vars.MONGODB_USER }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
      MONGODB_PROJECT_ID: ${{ vars.MONGODB_PROJECT_ID }}
      MONGODB_PROJECT_PRIVATE_KEY: ${{ secrets.MONGODB_PROJECT_PRIVATE_KEY }}
      MONGODB_PROJECT_PUBLIC_KEY: ${{ vars.MONGODB_PROJECT_PUBLIC_KEY }}
      MONGO_DB_PROD: ${{ vars.MONGODB_DB_PROD }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci
          npm install -g broken-link-checker

      - name: Check for dead links
        run: |
          export $(echo "${{ toJson(env) }}" | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]')
          broken-link-checker --recursive --exclude node_modules https://csp-example-rho.vercel.app/
