name: Check for dead links for app
on: push
jobs:
    dead-links-check:
      runs-on: ubuntu-latest
      env:
        secrets:
      steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g broken-link-checker
      - name: Create env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_MONGODB_PASSWORD=${{ secrets.NEXT_PUBLIC_MONGODB_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_MONGODB_PROJECT_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_MONGODB_PROJECT_PRIVATE_KEY }}" >> .env
          echo "NEXT_PUBLIC_MONGODB_DB_NAME=${{ vars.NEXT_PUBLIC_MONGODB_DB_NAME }}" >> .env
          echo "NEXT_PUBLIC_MONGODB_PROJECT_ID=${{ vars.NEXT_PUBLIC_MONGODB_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_MONGODB_PROJECT_PUBLIC_KEY=${{ vars.NEXT_PUBLIC_MONGODB_PROJECT_PUBLIC_KEY }}" >> .env
          echo "NEXT_PUBLIC_MONGODB_USER=${{ vars.NEXT_PUBLIC_MONGODB_USER }}" >> .env
          
          
      - name: Build Next.js app
        run: npm run build
        
      - name: Check for dead links
        run: broken-link-checker --recursive --exclude node_modules https://csp-example-rho.vercel.app/
