name: Check for dead links for app
on: push
env:
  MONGODB_USER: ${{ vars.MONGODB_USER }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD}}
  MONGODB_DB_NAME: "hi there"
  MONGODB_PROJECT_ID: ${{ vars.MONGODB_PROJECT_ID }}
  MONGODB_PROJECT_PRIVATE_KEY: ${{ secrets.MONGODB_PROJECT_PRIVATE_KEY }}
  MONGODB_PROJECT_PUBLIC_KEY: ${{ vars.MONGODB_PROJECT_PUBLIC_KEY }}
jobs:
    dead-links-check:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          npm ci
          npm install -g broken-link-checker
          
      - name: Build Next.js app
        run: npm run build
        
      - name: Check for dead links
        run: broken-link-checker --recursive --exclude node_modules https://csp-example-rho.vercel.app/
